global using FluentAssertions;
global using Moq;
global using JiApp.Scheduler.Domain;
global using JiApp.Scheduler.Persistence;
global using Microsoft.EntityFrameworkCore;
global using JiApp.Testing.Common.Assertions;
global using JiApp.Testing.Common.Bases;
global using JiApp.Testing.Common.Data;
global using JiApp.Testing.Common.Mocking;
global using static JiApp.Testing.Common.Assertions.ResultAssertions;
