#!/usr/bin/env bash
set -euo pipefail

# ── Helpers ──────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()    { echo -e "${CYAN}[INFO]${NC}    $*"; }
success() { echo -e "${GREEN}[OK]${NC}      $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}    $*"; }
error()   { echo -e "${RED}[ERROR]${NC}   $*"; }

# ── Flags ────────────────────────────────────────────────────────────────
RELEASE=false
INSTALL=false
CLEAN=false
PROD=false
DEV=false

for arg in "$@"; do
    case "$arg" in
        --release) RELEASE=true ;;
        --install) INSTALL=true ;;
        --clean)   CLEAN=true ;;
        --prod)    PROD=true ;;
        --dev)     DEV=true ;;
        --help|-h)
            echo "Usage: $0 [--prod|--dev] [--release] [--install] [--clean]"
            echo ""
            echo "  --prod       Build PRODUCTION (AWS) APK — Elastic IP gateway, Wake Lambda, prod CA"
            echo "  --dev        Build DEV (LAN) APK — dev machine IP, no Wake URL, dev CA"
            echo "  --release    Build release APK with signing + version bump"
            echo "  --install    Install APK to connected device via adb after build"
            echo "  --clean      Run gradlew clean before building"
            echo ""
            echo "  If neither --prod nor --dev is given and stdin is a TTY,"
            echo "  you will be prompted to choose interactively."
            echo ""
            echo "  Examples:"
            echo "    $0 --prod                        # debug prod APK"
            echo "    $0 --dev --release               # signed release dev APK"
            echo "    $0 --prod --release --install    # release prod + install to device"
            exit 0
            ;;
        *) echo "Unknown flag: $arg. Use --help for usage."; exit 1 ;;
    esac
done

# ── Mutual exclusion + env selection ─────────────────────────────────────
if $PROD && $DEV; then
    error "--prod and --dev are mutually exclusive"
    exit 1
fi

if ! $PROD && ! $DEV; then
    if [ -t 0 ]; then
        echo -ne "${CYAN}Build [p]rod (AWS) or [d]ev (LAN)? ${NC}"
        read -r choice
        case "$choice" in
            p|P|prod|PROD) PROD=true ;;
            d|D|dev|DEV)   DEV=true ;;
            *) error "Invalid choice '$choice' — expected p/prod or d/dev"; exit 1 ;;
        esac
    else
        error "No --prod or --dev flag and stdin is not a TTY."
        error "Pass --prod (AWS) or --dev (LAN) explicitly in non-interactive builds."
        exit 1
    fi
fi

# ── Paths ────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MOBILE_DIR="$SCRIPT_DIR/mobile"
ANDROID_DIR="$MOBILE_DIR/android"
GRADLE_FILE="$ANDROID_DIR/app/build.gradle"
KEYSTORE_FILE="$ANDROID_DIR/app/jiapp-release.keystore"
KEYSTORE_PROPS="$ANDROID_DIR/app/keystore.properties"
DIST_DIR="$SCRIPT_DIR/dist"

# ── Load .env ────────────────────────────────────────────────────────────
ENV_FILE="$MOBILE_DIR/.env"
GENERATED_CONFIG="$MOBILE_DIR/src/config.generated.ts"
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
    success ".env loaded"
else
    error ".env not found at $ENV_FILE"
    error "Copy mobile/.env.example to mobile/.env and configure it"
    exit 1
fi

# ── Resolve API / Wake URLs per selected env ─────────────────────────────
if $PROD; then
    API_BASE_URL="${JIAPP_API_URL:-}"
    WAKE_API_URL_VAL="${JIAPP_WAKE_API_URL:-}"
    CA_CERT_NAME="jiapp_prod_ca"
    if [ -z "$API_BASE_URL" ]; then
        error "JIAPP_API_URL not set in .env — required for PROD build"
        exit 1
    fi
else
    API_BASE_URL="${JIAPP_DEV_API_URL:-}"
    WAKE_API_URL_VAL=""
    CA_CERT_NAME="jiapp_dev_ca"
    if [ -z "$API_BASE_URL" ]; then
        error "JIAPP_DEV_API_URL not set in .env — required for DEV build"
        exit 1
    fi
fi

# ── Write generated config ───────────────────────────────────────────────
{
    echo "// Auto-generated by build-apk.sh from mobile/.env — DO NOT EDIT."
    echo "export const API_BASE_URL: string = '$API_BASE_URL';"
    if [ -n "$WAKE_API_URL_VAL" ]; then
        echo "export const WAKE_API_URL: string = '$WAKE_API_URL_VAL';"
    fi
} > "$GENERATED_CONFIG"
success "config.generated.ts written (API_BASE_URL=$API_BASE_URL)"

# ── Network security config ──────────────────────────────────────────────
NETWORK_SECURITY_CONFIG="$ANDROID_DIR/app/src/main/res/xml/network_security_config.xml"

# Always clear previously injected domains in both blocks
sed -i '/<!-- DEVICE_IP_BEGIN -->/,/<!-- DEVICE_IP_END -->/{ /<!-- DEVICE_IP_BEGIN -->/!{ /<!-- DEVICE_IP_END -->/!d; }; }' \
    "$NETWORK_SECURITY_CONFIG"
sed -i '/<!-- PROD_IP_BEGIN -->/,/<!-- PROD_IP_END -->/{ /<!-- PROD_IP_BEGIN -->/!{ /<!-- PROD_IP_END -->/!d; }; }' \
    "$NETWORK_SECURITY_CONFIG"

if $PROD; then
    # ── Prod build: inject JIAPP_PROD_IP ─────────────────────────────────
    if [ -n "${JIAPP_PROD_IP:-}" ]; then
        sed -i "s|<!-- PROD_IP_BEGIN -->|&\n        <domain includeSubdomains=\"false\">$JIAPP_PROD_IP</domain>|" \
            "$NETWORK_SECURITY_CONFIG"
        success "Injected PROD_IP=$JIAPP_PROD_IP into network_security_config.xml (prod-CA block)"
    else
        warn "JIAPP_PROD_IP not set in .env — production CA domain not injected"
    fi
else
    # ── Dev build: inject dev machine LAN IP ─────────────────────────────
    DEVICE_HOST=$(echo "$API_BASE_URL" | sed -E 's|^https?://([^:/]+).*|\1|')
    if [ -n "$DEVICE_HOST" ] && [ "$DEVICE_HOST" != "10.0.2.2" ] && [ "$DEVICE_HOST" != "localhost" ]; then
        sed -i "s|<!-- DEVICE_IP_BEGIN -->|&\n        <domain includeSubdomains=\"false\">$DEVICE_HOST</domain>|" \
            "$NETWORK_SECURITY_CONFIG"
        success "Injected $DEVICE_HOST into network_security_config.xml (dev-CA block)"
    else
        info "Using emulator/localhost — no extra domain needed in network_security_config.xml"
    fi
fi

# ── CA cert for Android network security ─────────────────────────────────
CA_CERT="$ANDROID_DIR/app/src/main/res/raw/$CA_CERT_NAME"
if [ ! -f "$CA_CERT" ]; then
    if $DEV; then
        # Dev CA can be auto-extracted from the backend dev-cert.pfx
        PFX_FILE="$SCRIPT_DIR/backend/certs/dev-cert.pfx"
        info "Dev CA cert not found — attempting to extract from dev-cert.pfx..."
        if [ -f "$PFX_FILE" ]; then
            PFX_PASS="JiAppDev2026!"
            if [ -f "$SCRIPT_DIR/backend/.env" ]; then
                BACKEND_PASS=$(grep -oP 'DEV_CERT_PASSWORD=\K.*' "$SCRIPT_DIR/backend/.env" 2>/dev/null || true)
                [ -n "$BACKEND_PASS" ] && PFX_PASS="$BACKEND_PASS"
            fi
            if openssl pkcs12 -in "$PFX_FILE" -nokeys -passin "pass:$PFX_PASS" 2>/dev/null \
                | openssl x509 -outform DER -out "$CA_CERT" 2>/dev/null; then
                success "Dev CA cert extracted to res/raw/$CA_CERT_NAME"
            else
                warn "Failed to extract CA cert — HTTPS to dev server may not work"
                warn "Run manually: openssl pkcs12 -in backend/certs/dev-cert.pfx -nokeys \\"
                warn "    | openssl x509 -outform DER -out $CA_CERT"
            fi
        else
            warn "dev-cert.pfx not found — run backend/start-dev.sh first to create it"
            warn "Without the CA cert, HTTPS to the dev server may fail on physical devices"
        fi
    else
        warn "Prod CA cert ($CA_CERT_NAME) not found in res/raw/"
        warn "The production CA must be placed at $CA_CERT manually"
    fi
else
    success "CA cert present: $CA_CERT_NAME"
fi
echo ""

# ── Prerequisites ────────────────────────────────────────────────────────
check_prerequisites() {
    info "Checking prerequisites..."

    # Node.js
    if ! command -v node &>/dev/null; then
        error "Node.js is not installed. Please install Node.js >= 22.11.0"
        exit 1
    fi
    local node_ver
    node_ver=$(node --version | sed 's/v//' | cut -d. -f1)
    if [ "$node_ver" -lt 22 ]; then
        error "Node.js >= 22.11.0 required, found $(node --version)"
        exit 1
    fi
    success "Node.js $(node --version)"

    # Java
    if ! command -v java &>/dev/null; then
        error "Java is not installed. Please install JDK 17+"
        exit 1
    fi
    success "Java $(java --version 2>&1 | head -1)"

    # Android SDK
    if [ -z "${ANDROID_HOME:-}" ]; then
        # Check common locations
        if [ -d "$HOME/Android/Sdk" ]; then
            export ANDROID_HOME="$HOME/Android/Sdk"
        elif [ -d "$HOME/android-sdk" ]; then
            export ANDROID_HOME="$HOME/android-sdk"
        else
            error "ANDROID_HOME is not set and no SDK found in common locations."
            error "Set ANDROID_HOME or install Android Studio."
            exit 1
        fi
    fi
    success "Android SDK at $ANDROID_HOME"

    # adb (only needed for --install)
    if $INSTALL; then
        if ! command -v adb &>/dev/null; then
            error "adb is required for --install but not found in PATH"
            exit 1
        fi
        success "adb available"
    fi

    # keytool (only needed for --release)
    if $RELEASE; then
        if ! command -v keytool &>/dev/null; then
            error "keytool is required for --release (part of JDK)"
            exit 1
        fi
    fi

    echo ""
}

# ── Dependencies ─────────────────────────────────────────────────────────
install_deps() {
    if [ -d "$MOBILE_DIR/node_modules" ]; then
        info "node_modules/ found, skipping npm install"
        return
    fi
    info "Installing npm dependencies..."
    (cd "$MOBILE_DIR" && npm install)
    success "npm install complete"
    echo ""
}

# ── Keystore setup (release only) ────────────────────────────────────────
setup_keystore() {
    if [ -f "$KEYSTORE_FILE" ] && [ -f "$KEYSTORE_PROPS" ]; then
        info "Release keystore already exists, skipping generation"
        return
    fi

    info "Generating release keystore..."

    local storepass keypass
    storepass=$(openssl rand -base64 24 2>/dev/null || echo "jiapp-release-$(date +%s)")
    keypass="$storepass"

    keytool -genkeypair -v \
        -keystore "$KEYSTORE_FILE" \
        -alias jiapprelease \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -storepass "$storepass" \
        -keypass "$keypass" \
        -dname "CN=JiApp, OU=Development, O=JiApp, L=Unknown, ST=Unknown, C=US" \
        2>/dev/null

    cat > "$KEYSTORE_PROPS" <<EOF
storeFile=jiapp-release.keystore
storePassword=$storepass
keyAlias=jiapprelease
keyPassword=$keypass
EOF

    success "Release keystore generated"
    success "keystore.properties written (gitignored — do not commit)"
    echo ""
}

# ── Version bump (release only) ──────────────────────────────────────────
bump_version() {
    local version_code
    version_code=$(grep -oP 'versionCode \K\d+' "$GRADLE_FILE")

    if [ -z "$version_code" ]; then
        error "Could not read versionCode from $GRADLE_FILE"
        exit 1
    fi

    local new_code=$((version_code + 1))

    sed -i "s/versionCode $version_code/versionCode $new_code/" "$GRADLE_FILE"

    success "versionCode bumped: $version_code → $new_code"
    echo ""
}

# ── Build ────────────────────────────────────────────────────────────────
build_apk() {
    local variant="$1"  # Debug or Release

    info "Building $variant APK..."

    cd "$ANDROID_DIR"

    if $CLEAN; then
        info "Running gradlew clean..."
        ./gradlew clean 2>&1 | tail -5
    fi

    local task="assemble$variant"
    local gradle_output gradle_exit=0

    set +e
    gradle_output=$(./gradlew "$task" 2>&1)
    gradle_exit=$?
    set -e

    echo "$gradle_output" | tail -20

    if [ "$gradle_exit" -ne 0 ]; then
        error "Gradle build failed (exit code: $gradle_exit)"
        exit 1
    fi

    cd "$SCRIPT_DIR"
    success "$variant build complete"
    echo ""
}

# ── Copy to dist ─────────────────────────────────────────────────────────
copy_to_dist() {
    local variant="$1"  # debug or release
    local version_code
    version_code=$(grep -oP 'versionCode \K\d+' "$GRADLE_FILE")

    mkdir -p "$DIST_DIR"

    local apk_src apk_dst
    apk_src="$ANDROID_DIR/app/build/outputs/apk/$variant/app-$variant.apk"
    apk_dst="$DIST_DIR/JiAppMobile-${version_code}-${variant}.apk"

    if [ ! -f "$apk_src" ]; then
        error "APK not found at $apk_src"
        exit 1
    fi

    cp "$apk_src" "$apk_dst"

    local size
    size=$(du -h "$apk_dst" | cut -f1)
    success "APK copied: $apk_dst ($size)"
    echo ""
}

# ── Install to device ────────────────────────────────────────────────────
install_to_device() {
    local variant="$1"
    local version_code
    version_code=$(grep -oP 'versionCode \K\d+' "$GRADLE_FILE")
    local apk_path="$DIST_DIR/JiAppMobile-${version_code}-${variant}.apk"

    info "Waiting for device..."
    adb wait-for-device 2>&1 | tail -1

    info "Installing APK to device..."
    adb install -r "$apk_path"

    success "APK installed to device"
    echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       JiApp Mobile — APK Build Script        ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""

check_prerequisites
install_deps

# ── Build banner ──────────────────────────────────────────────────────────
if $PROD; then
    echo -e "${CYAN}==> Building PROD APK  | API=$API_BASE_URL  WAKE=${WAKE_API_URL_VAL:-none}  CA=$CA_CERT_NAME${NC}"
else
    echo -e "${CYAN}==> Building DEV APK   | API=$API_BASE_URL  WAKE=none  CA=$CA_CERT_NAME${NC}"
fi
echo ""

if $RELEASE; then
    setup_keystore
    bump_version
    build_apk "Release"
    copy_to_dist "release"
    if $INSTALL; then
        install_to_device "release"
    fi
else
    build_apk "Debug"
    copy_to_dist "debug"
    if $INSTALL; then
        install_to_device "debug"
    fi
fi

echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Build complete!                  ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
