services:
  identity:
    build:
      context: .
      dockerfile: ./src/JiApp.Identity/Dockerfile
    ports:
      - "6701:6701"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  ytdownloader:
    build:
      context: .
      dockerfile: ./src/JiApp.YtDownloader/Dockerfile
    ports:
      - "6702:6702"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  imagetools:
    build:
      context: .
      dockerfile: ./src/JiApp.ImageTools/Dockerfile
    ports:
      - "6703:6703"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  scheduler:
    build:
      context: .
      dockerfile: ./src/JiApp.Scheduler/Dockerfile
    ports:
      - "6704:6704"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  lovingboards:
    build:
      context: .
      dockerfile: ./src/api.JiApp.LovingBoards/Dockerfile
    ports:
      - "6705:6705"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  gateway:
    build:
      context: .
      dockerfile: ./src/JiApp.Gateway/Dockerfile
    ports:
      - "6700:6700"
    depends_on:
      - identity
      - ytdownloader
      - imagetools
      - scheduler
      - lovingboards
