global using System.Net;
global using System.Text.Json;
global using FluentAssertions;
global using JiApp.Common.Abstractions;
global using JiApp.Gateway.RateLimiting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.RateLimiting;
global using Microsoft.Extensions.Primitives;
global using Moq;